version: v0.0.1
services:
  muleesb-lb:
    image: rancher/load-balancer-service
    links:
      - muleesb
    ports:
      - ${lb_port}:5432

  muleesb:
    image: vromero/mule
    environment:
      INSTANCE_NAME: ${instance_name}
      PORT: ${port}
      APP_DIR: ${app_dir}
      LOG_DIR: ${log_dir}
    tty: true
    stdin_open: true
    
